name: Change README

on:
  schedule:
    - cron: '0 23 * * *'
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  display:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Display README
        run: |
          hour=$(TZ=Asia/Tokyo date +%H)
          if [ $hour -ge 8 ] && [ $hour -lt 22 ]; then
            cat README-day.md > README.md
          else
            cat README-night.md > README.md
          fi
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Display README"
          git push
