name: Change README

on:
  schedule:
    - cron: '0 22 * * *'
    - cron: '0 2 * * *'
    - cron: '0 3 * * *'
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  display:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Display README
        run: |
          hour=$(TZ=Asia/Tokyo date +%H)
          if [ $hour -ge 6 ] && [ $hour -lt 12 ]; then
            cat README-morning.md > README.md
          elif [ $hour -ge 12 ] && [ $hour -lt 18 ]; then
            cat README-day.md > README.md
          else 
            cat README-night.md > README.md
          fi
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Update weather in README
        run: python weather.py
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      - name: Commit changes
        run: |
          git config user.name ${{ github.repository_owner }}
          git config user.email ${{ secrets.GIT_EMAIL}}
          git add README.md
          git commit -m "Display README"
          git push
