name: Change README

on:
  schedule:
    - cron: '0 0,9,18 * * *' # 0:00, 9:00, 18:00 JST (日中)
    - cron: '0 3,15,21 * * *' # 3:00, 15:00, 21:00 JST (夜間)

jobs:
  change-readme-day:
    runs-on: ubuntu-latest
    if: ${{ github.event.schedule[0] }}
    steps:
      - name: Update README for daytime
        run: |
          # 日中向けの内容を記述するコマンドをここに書く
          echo "Hello, it's daytime in Japan!" > README.md

  change-readme-night:
    runs-on: ubuntu-latest
    if: ${{ github.event.schedule[1] }}
    steps:
      - name: Update README for nighttime
        run: |
          # 夜間向けの内容を記述するコマンドをここに書く
          echo "Good evening, it's nighttime in Japan!" > README.md
